name: 🚀 Deploy Docker Laravel
on:
    push:
        branches:
            - main

jobs:
    web-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.1.2"

            - name: Install Composer dependencies
              run: composer install --no-interaction --no-suggest

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to Azure VM
              run: |
                  ssh -o StrictHostKeyChecking=no azureuser@172.174.168.214 << 'EOF'
                  cd ngnix/docker-ngnix-laravel
                  git pull origin main || { echo 'Git pull failed'; exit 1; }
                  docker compose down
                  docker compose build --no-cache 
                  docker compose up -d
                  docker exec -it dockerApp bash
                  composer install --no-interaction --no-suggest
                  php artisan config:cache
                  php artisan route:cache
                  php artisan view:clear
                  EOF
